// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompModels.DAL.Models;

public partial class BezierResultsPhysicalFile
{
    public long Id { get; set; }

    public string FileNameWithoutDotAndExtension { get; set; }

    public string Extension { get; set; }

    public byte[] FileContent { get; set; }

    public virtual ICollection<BezierRequestFile> BezierRequestFiles { get; set; } = new List<BezierRequestFile>();
}