// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompModels.DAL.Models;

/// <summary>
/// Параметры запроса и ответа (если уже рассчитано). Физические файлы - в др. таблице и табл. связи.
/// </summary>
public partial class BezierCalculationRequest
{
    public long Id { get; set; }

    public int UserRequesterId { get; set; }

    /// <summary>
    /// without time zone!!!
    /// </summary>
    public DateTime RequestedAt { get; set; }

    public int X { get; set; }

    public int Y { get; set; }

    /// <summary>
    /// nullable. есть 2D.
    /// </summary>
    public int? Z { get; set; }

    public float DesiredPorosity { get; set; }

    public float FibreDiameter { get; set; }

    public short RequestStatusId { get; set; }

    /// <summary>
    /// null. до конца  расчета его нет.
    /// </summary>
    public float? CalcResultPorosity { get; set; }

    public virtual ICollection<BezierRequestFile> BezierRequestFiles { get; set; } = new List<BezierRequestFile>();

    public virtual RequestsStatusesHandbook RequestStatus { get; set; }
}