// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompModels.DAL.Models;

/// <summary>
/// Связь заявки на расчет и файлов результата.
/// </summary>
public partial class BezierRequestFile
{
    public long Id { get; set; }

    public long ExperimentId { get; set; }

    public long FileId { get; set; }

    public virtual BezierCalculationRequest Experiment { get; set; }

    public virtual BezierResultsPhysicalFile File { get; set; }
}