// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompModels.DAL.Models;

public partial class ComputationalModel
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsCellularAutomaton { get; set; }

    public bool IsPorousModel { get; set; }

    public DateTime CreatedAt { get; set; }

    public string InputParamsJsonExample { get; set; }

    public string OutputParamsJsonExample { get; set; }

    public Guid CreatedBy { get; set; }

    public string Description { get; set; }
}