// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompModels.DAL.Models;

public partial class ComputationalModel
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsCellularAutomaton { get; set; }

    public bool IsPorousModel { get; set; }

    public bool IsVisible { get; set; }

    public DateTime CreatedAt { get; set; }

    public long CreatedBy { get; set; }

    public TimeOnly? LastUpdatedAt { get; set; }

    public long? LastUpdatedBy { get; set; }
}