// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompModels.DAL.Models;

public partial class RequestsStatusesHandbook
{
    public short Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BezierCalculationRequest> BezierCalculationRequests { get; set; } = new List<BezierCalculationRequest>();
}