// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NatureExperiments.DAL.Models;

public partial class NatureExperimentsNatureExperimentsPhysicalAttachment
{
    public long Id { get; set; }

    public long ExperimentId { get; set; }

    public long FileId { get; set; }

    public virtual NatureExperiment Experiment { get; set; }

    public virtual NatureExperimentsPhysicalAttachment File { get; set; }
}