// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NatureExperiments.DAL.Models;

public partial class NatureExperiment
{
    public long Id { get; set; }

    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public long CreatedBy { get; set; }

    public DateTime LastUpdatedAt { get; set; }

    public long LastUpdatedBy { get; set; }

    public string Description { get; set; }

    public virtual ICollection<NatureExperimentsNatureExperimentsPhysicalAttachment> NatureExperimentsNatureExperimentsPhysicalAttachments { get; set; } = new List<NatureExperimentsNatureExperimentsPhysicalAttachment>();
}